// Steema.TeeTree.VCL.xxx packages.
// Common assembly attributes

[assembly: AssemblyTitle('TeeTree')]
[assembly: AssemblyDescription('Diagram and FlowChart Controls by David Berneda')]
[assembly: AssemblyConfiguration('TeeTree for VCL.NET')]
[assembly: AssemblyCompany('Steema Software')]
[assembly: AssemblyProduct('TeeTree')]
[assembly: AssemblyCopyright('2003-2004 by Steema Software. All Rights Reserved.')]
[assembly: AssemblyTrademark('')]
[assembly: AssemblyCulture('')]
[assembly: AssemblyVersion('2.0.*')]
[assembly: AssemblyDelaySign(false)]

{$IFDEF TEEKEYS}
[assembly: AssemblyKeyFile('Keys\\TeeChart.snk')]
{$ENDIF}

[assembly: AssemblyKeyName('')]

