// Steema.TeeChart.VCL.xxx packages.
// Common assembly attributes

{$IFDEF TEELITE}
[assembly: AssemblyTitle('TeeChart Standard')]
{$ELSE}
[assembly: AssemblyTitle('TeeChart Pro')]
{$ENDIF}

[assembly: AssemblyDescription('Charting Controls by David Berneda')]
[assembly: AssemblyConfiguration('TeeChart for VCL.NET')]
[assembly: AssemblyCompany('Steema Software')]
[assembly: AssemblyProduct('TeeChart')]
[assembly: AssemblyCopyright('(c) 2003-2006 by Steema Software. All Rights Reserved.')]
[assembly: AssemblyTrademark('')]
[assembly: AssemblyCulture('')]
[assembly: AssemblyVersion('8.0.0.*')]
[assembly: AssemblyDelaySign(false)]

{$IFDEF TEEKEYS}
[assembly: AssemblyKeyFile('Keys\\TeeChart.snk')]
{$ENDIF}

[assembly: AssemblyKeyName('')]

