
{                                                                              }
{  IB_UserClasses.inc                                                          }
{                                                                              }

// This file contains a lookup table of classes that are used in the generic
// template that provides all properties, methods, events with an IBO aware
// control.  These classes are "user" defined - not IBO natives.

{$IFDEF IBC_BitCheckBox}  TIB_CustomBitCheckBox.  {$ENDIF}
{$IFDEF IBC_BitCheckList} TIB_CustomBitCheckList. {$ENDIF}
