program TeeTree2New;
{$I TeeDefs.inc}

{%DotNetAssemblyCompiler '..\..\..\..\..\windows\microsoft.net\framework\v1.1.4322\System.Drawing.dll'}

uses
  {$IFDEF CLX}
  QForms,
  {$ELSE}
  Forms,
  {$ENDIF}
  TreeMain in 'TreeMain.pas' {TreeMain.TTeeTree2Form: Borland.Vcl.Forms.TForm},
  Main in 'Main.pas' {Main.TWelcomeForm: Borland.Vcl.Forms.TForm},
  Base in 'Base.pas' {BaseForm},
  Starting in 'Starting.pas' {StartingForm},
  Ordering in 'Ordering.pas' {OrderingForm},
  NodeBorder in 'NodeBorder.pas' {NodeBorderForm},
  TextAlignment in 'TextAlignment.pas' {TextAlignForm},
  ClipText in 'ClipText.pas' {ClipTextForm},
  AddChildNode in 'AddChildNode.pas' {AddChildrenForm},
  NodeBrush in 'NodeBrush.pas' {NodeBrushForm},
  NodeCursor in 'NodeCursor.pas' {NodeCursorForm},
  NodeFont in 'NodeFont.pas' {NodeFontForm},
  NodeGradient in 'NodeGradient.pas' {NodeGradientForm},
  NodeShadow in 'NodeShadow.pas' {NodeShadowForm},
  NodeStyle in 'NodeStyle.pas' {NodeStyleForm},
  NodeTransparency in 'NodeTransparency.pas' {NodeTranspForm},
  TextAngle in 'TextAngle.pas' {TextAngleForm},
  NodeImageIndex in 'NodeImageIndex.pas' {NodeImageIndexForm},
  ImageLevels in 'ImageLevels.pas' {ImageLevelsForm},
  SortingNodes in 'SortingNodes.pas' {SortingNodesForm},
  BufferedDisplay in 'BufferedDisplay.pas' {BufferedDisplayForm},
  TreeBackImage in 'TreeBackImage.pas' {BackImageForm},
  ImageZoom in 'ImageZoom.pas' {ImageZoomForm},
  NodeImageAlign in 'NodeImageAlign.pas' {NodeImageAlignForm},
  TextExportImport in 'TextExportImport.pas' {TextExportImportForm},
  ExpandCollapse in 'ExpandCollapse.pas' {ExpandCollapseForm},
  CreateOnDemand in 'CreateOnDemand.pas' {CreateOnDemandForm},
  NodeEvents in 'NodeEvents.pas' {NodeEventsForm},
  NodeAutoSize in 'NodeAutoSize.pas' {NodeAutoSizeForm},
  NodeDataTag in 'NodeDataTag.pas' {NodeDataForm},
  NodeDrawOrder in 'NodeDrawOrder.pas' {NodeDrawOrderForm},
  NodeHints in 'NodeHints.pas' {NodeHintsForm},
  TreeImageList in 'TreeImageList.pas' {TreeImageListForm},
  NodeImageSize in 'NodeImageSize.pas' {NodeImageSizeForm},
  NodeLevel in 'NodeLevel.pas' {NodeLevelForm},
  TreeSpeed in 'TreeSpeed.pas' {TreeSpeedForm},
  TreeGradient in 'TreeGradient.pas' {TreeGradientForm},
  TreeGrid in 'TreeGrid.pas' {TreeGridForm},
  TreeAllowDelete in 'TreeAllowDelete.pas' {TreeAllowDeleteForm},
  CircularAlign in 'CircularAlign.pas' {CircularAlignForm},
  PolygonShape in 'PolygonShape.pas' {PolygonShapeForm},
  TreeOffice in 'TreeOffice.pas' {TreeOfficeForm},
  DragFromEdit in 'DragFromEdit.pas' {DragFromEditForm},
  DragDropSingle in 'DragDropSingle.pas' {DragDropSingleForm},
  ScrollBars in 'ScrollBars.pas' {ScrollBarsForm},
  HotTrack in 'HotTrack.pas' {HotTrackForm},
  Scrolling in 'Scrolling.pas' {ScrollingForm},
  Zooming in 'Zooming.pas' {ZoomingForm},
  EditorPanel in 'EditorPanel.pas' {EditorPanelForm},
  MouseWheel in 'MouseWheel.pas' {MouseWheelForm},
  CustomShape in 'CustomShape.pas' {CustomShapeForm},
  CrossBox in 'CrossBox.pas' {CrossBoxForm},
  CustomDraw in 'CustomDraw.pas' {CustomDrawForm},
  DesignMode in 'DesignMode.pas' {DesignModeForm},
  ClipboardCopy in 'ClipboardCopy.pas' {ClipboardCopyForm},
  PrintPreviewPanel in 'PrintPreviewPanel.pas' {PrintPreviewPanelForm},
  BrotherIndex in 'BrotherIndex.pas' {BrotherIndexForm},
  RemoveNodes in 'RemoveNodes.pas' {RemoveNodesForm},
  AddMethods in 'AddMethods.pas' {AddMethodsForm},
  OtherComponents in 'OtherComponents.pas' {OtherComponentsForm},
  TopBottomAlign in 'TopBottomAlign.pas' {TopBottomAlignForm},
  LeftRightAlign in 'LeftRightAlign.pas' {LeftRightAlignForm},
  ExplorerAlign in 'ExplorerAlign.pas' {ExplorerAlignForm},
  ExplorerRightAlign in 'ExplorerRightAlign.pas' {ExplorerRightAlignForm},
  ListViewAlign in 'ListViewAlign.pas' {ListViewAlignForm},
  SaveLoadFile in 'SaveLoadFile.pas' {SaveLoadFileForm},
  ConnectionAdd in 'ConnectionAdd.pas' {ConnectionAddForm},
  ConnectionFormat in 'ConnectionFormat.pas' {ConnectionFormatForm},
  ConnectionText in 'ConnectionText.pas' {ConnectionTextForm},
  Animations in 'Animations.pas' {AnimationsForm},
  TreeRuler in 'TreeRuler.pas' {TreeRulerForm},
  TreePageNavigator in 'TreePageNavigator.pas' {TreePageNavigatorForm},
  TreeEdit in 'TreeEdit.pas' {TreeEditForm},
  Exporting in 'Exporting.pas' {ExportingForm},
  AddingText in 'AddingText.pas' {AddingTextForm},
  PolylineShape in 'PolylineShape.pas' {PolylineShapeForm},
  GridShape in 'GridShape.pas' {GridShapeForm},
  MultiColumn in 'MultiColumn.pas' {MultiColumnForm},
  ConnectionPoints in 'ConnectionPoints.pas' {ConnectionPointsForm},
  TreeComponent in 'TreeComponent.pas' {TreeComponentForm},
  TreeReadOnly in 'TreeReadOnly.pas' {TreeReadOnlyForm},
  BaseDB in 'BaseDB.pas' {BaseDBForm},
  DBTreeComponent in 'DBTreeComponent.pas' {DBTreeComponentForm},
  DBTreeWizard in 'DBTreeWizard.pas' {DBTreeWizardForm},
  DBTreeMasterDetail in 'DBTreeMasterDetail.pas' {DBTreeMasterDetailForm},
  DBTreeGroup in 'DBTreeGroup.pas' {DBTreeGroupForm},
  DBTreeFormat in 'DBTreeFormat.pas' {DBTreeFormatForm},
  InspectorComponent in 'InspectorComponent.pas' {TeeInspectorForm},
  TreeRoots in 'TreeRoots.pas' {TreeRootsForm},
  TreeShapes in 'TreeShapes.pas' {TreeShapesForm},
  DragDropMultiTree in 'DragDropMultiTree.pas' {DragDropMultiForm},
  ExportXMLExcel in 'ExportXMLExcel.pas' {ExportXMLExcelForm},
  Monochrome in 'Monochrome.pas' {MonochromeForm},
  CustomInspector in 'CustomInspector.pas' {CustomInspectorForm},
  TreeConnections in 'TreeConnections.pas' {TreeConnectionsForm},
  TreeSelected in 'TreeSelected.pas' {TreeSelectedForm},
  SelectingNodes in 'SelectingNodes.pas' {SelectingNodesForm},
  NodeHandles in 'NodeHandles.pas' {HandlesForm},
  KeyboardNavigation in 'KeyboardNavigation.pas' {TreeNavigationForm},
  GlobalFormat in 'GlobalFormat.pas' {GlobalFormatForm},
  ZoomScroll in 'ZoomScroll.pas' {ZoomScrollForm};

{$R *.RES}

{$IFDEF CLR}
[STAThread]
{$ENDIF}
begin
  Application.Initialize;
  Application.Title := 'TeeTree v2 - What''s New !';
  Application.CreateForm(TTeeTree2Form, TeeTree2Form);
  Application.Run;
end.
