DELETE FROM  ARACHAR;
DELETE FROM  ARAC_RUHSAT;
DELETE FROM  ARAC;
DELETE FROM SEFER;
DELETE FROM FAT_IRS;
DELETE FROM FATURA_D;
DELETE FROM FAT_IRS_ACK;
DELETE FROM FAT_IRS_AKTAR;
DELETE FROM CARIHAR;
DELETE FROM CARIHAR_DOV;
DELETE FROM CARI_AY;
delete FROM CARI_GRUP;
DELETE FROM CARI_GRUP_UYE;
DELETE from CARI_SEVKAD;
DELETE FROM CARI;
DELETE FROM DEKONT_D;
DELETE FROM DEKONT;
DELETE FROM  DOVKUR;
DELETE FROM  KASAHAR;
DELETE FROM  KASA_AY;
DELETE FROM  KASA;
DELETE FROM  MAZOT_FISI;
DELETE FROM  PERSONEL_HAR;
DELETE FROM  PERSONEL;
DELETE FROM  URUNHAR;













